rakenduste-programmeerimine-2023/learner

app/layout.tsx, package-lock.json, package.json
This also adds `mui/icons-material` to `package.json`. May need to run `npm install @mui/icons-material` in terminal before running the project.
=> style: update navbar styling to use MUI components, closes #4

app/layout.tsx, app/user/User.jsx, package-lock.json, package.json
- Added routing for navbar
- Created login/profile functionality (if not logged in -> show login btn, if logged in -> show profile btn)
- Created user folder and User.jsx file
For changes to work on local you need to:
**install: `npm i @supabase/auth-helpers-nextjs`**
**change `.env.local.example` file to `.env.local` and add your SUPABASE_URL and SUPABASE_ANON_KEY**
=> issue-16: routing for nav, login/profile, user file, closes #16

app/createForm/page.tsx, app/layout.tsx, app/page.tsx, app/profile/page.tsx
Added logout button to profile page, cleaned main page code and added some css.
=> issue-8: login/out, signup, closes #8

app/page.tsx, components/InspirationalQuote.tsx
This calls an external API containing a random setup and punchline for a joke.
This is currently being shown to both signed in and not logged in users.
=> feat(api): fetch external API to main page, closes #15

supabase/migrations/20231115163805_category.sql, supabase/migrations/20231116121920_favorite.sql, supabase/migrations/20231116121936_form.sql, supabase/migrations/20231116121943_question.sql, supabase/migrations/20231116121953_history.sql, supabase/migrations/20231116134245_user.sql
Created tables (user, category, favorite, form, question, history)
Enabled RLS to all tables, added policies to user table. Policies for other tables have to be added later!
User table doesn't have email and password, they are stored in supabase auth db
=> refactor: create db tables, closes #24

app/layout.tsx, app/profile/page.tsx, components/AuthButton.tsx
Added initial setup for profile page UI, may need to create a seperate css file
=> style: add initial UI to profile page, closes #26

supabase/migrations/20231116134245_user.sql, supabase/seed.sql
Replaced " with ' in seed file. Remember this in the future!
Commented out history insertion, this need user_id, but we have no users at the moment. 
Fixed minor spelling errors.
=> bugfix: column "cats" does not exist, closes #37

components/MainPageForms.jsx
Changed form url in `MainPageForms` `'/form/'+formID` -> `'/form?form_id='+formID`
=> refactor: change form url, closes #40

components/ViewQuestion.jsx
Added title fetching and showing
Added buttons to move between questions
Changed html elements to MUI elements
=> feat: add title and buttons to form page, closes #51

app/createForm/page.jsx, app/globals.css, package-lock.json, package.json, supabase/migrations/20231116121936_form.sql
Not working yet - asking for help with finding a solution. Currently it can't authenticate the user and therefore can't save the data.
=> Feature/issue 42/create form page, closes #42

app/results/page.tsx, components/ViewQuestion.jsx
Added a `TextField` for inserting anwsers, as well a a `Button` for completing the form and displaying the results.
Made a new route named `results` that fetches all questions and correct answers from the form along with user's given answers using `localStorage`. The user can then compare their answer for each question with the correct answer.
Note: the `TextField` component is hard to see since the border and text color of it is the same as the page's background color if it's not highlighted. To highlight it, click above the "FINISH" button and type in your answer.
=> feat: add statistics view, closes #52

app/createForm/page.jsx, package-lock.json, package.json
- "form" table now saves user_id
- installed date-fns
=> bug fix, closes #56

components/MainPageForms.jsx
Added rules: 
if user is not signed in: show only forms with `status 3`
if user is signed in: show forms with `status 3, 2` and checks if forms with `status 1` have matching `userID`
Minor changes to UI
=> feat: main page form showing rules, closes #59

components/AuthButton.tsx
Refactored whole AuthButton component to 'use client'
Changed HTML elements to MUI
=> bugfix: fixed error on profile page, closes #71

app/profile/page.tsx, components/ShowUserFavorites.tsx
user favorite forms are now shown on profile page
=> feature: show user favorite forms on profile page, closes #58

app/changePassword/page.tsx, app/profile/page.tsx
Added change password functionality
User is redirected to new route and can change their password there
Added validation messages, but errors are shown in English because they are from supabase
=> Feature: change password functionality, closes #45

components/ViewQuestion.jsx, supabase/migrations/20231116121953_history.sql
Added function to insert or update history table when user completes form
Fixed user id error in ViewQuestion when page is refreshed
=> feat: user form history to db, closes #94

components/ViewQuestion.jsx
Added icon to questions page to mark them, if clicked it creates an icon on the button
=> feat: users can mark questions, closes #96

components/MainPageForms.jsx, components/ViewQuestion.jsx
Added validation to form - button `Lõpeta` is disabled until all answers are filled
Added checks to functions that insert to db, so when user is not signed in, there are no errors
Removed one console log from `MainPageForms`
=> feat: validate form inputs, closes #98

supabase/seed.sql
Created more categories, as well as more forms by adding more sample data for `category`, `form` and `question` tables.
This should speed up our testing process.
=> feat(db); add more sample data, closes #106

components/ShowUserForms.tsx, supabase/migrations/20231116121936_form.sql
Added button to delete form, which updated forms `deleted` timestamp to current
Added control to form fetching which checks if deleted is not less than current
Added order by to fetching
Added `updated` timestamp when user changes form status 
Changed HTML to MUI elements
=> Feat: users can delete their forms, closes #102

app/createForm/page.jsx, components/SaveNewCategory.tsx, supabase/migrations/20231115163805_category.sql
Added feature so users can add new categories on `CreateForm` page
=> feat: users can add new cateogries, closes #101

app/profile/page.tsx, components/ShowUserFavorites.tsx, components/ShowUserForms.tsx, components/ShowUserHistory.tsx
`ShowUserFavorites` and `ShowUserForms` components now display forms horizontally.
Relocated components in `app/profile` page under child `Grid` element to better fit with horizontal allignment.
Small changes to `gap` props.
=> style: horizontal allignment for form components, closes #108

app/results/page.tsx, components/ViewQuestion.jsx
At the moment it only works for a logged in user. Need to find a solution for logged out user.
=> feat: add button and its functionality for user

components/MainPageForms.jsx, components/ShowUserFavorites.tsx, components/ShowUserForms.tsx, components/ShowUserHistory.tsx
Added check to front page form fetching to not include deleted forms
Removed some (or many) console logs
=> Fix: front page shows only not deleted forms, closes #116

app/profile/page.tsx, components/ChangePassword.tsx
Changed password changing component to modal, instead of route
=> Refactor: change password as modal, closes #143

components/SuggestedForms.tsx
I had no way to test if this works now or not, so please try it out and let me know if user's deleted forms are visible under suggested forms or not. Don't forget that in order to see the suggested forms you made, you have to log out.
=> refactor: change deleted query, closes #140

components/ShowUserForms.tsx
Should order user forms so that more recent forms are shown first.
Please test this out yourself before approving!
=> style: order user forms by creation time desc, closes #141

app/layout.tsx, app/page.tsx, app/profile/page.tsx, components/AuthButton.tsx, components/InspirationalQuote.tsx, components/MainPageForms.jsx, components/Navbar.tsx, components/ShowUserFavorites.tsx, components/ShowUserForms.tsx, components/ShowUserHistory.tsx, components/SuggestedForms.tsx, components/ThemeRegistry/theme.ts, components/ViewQuestion.jsx
Added typography global styles
Changed bunch of files, I'm sure there will be many conflicts, but please check every page and let me know what else needs fixing
=> Style: global CSS, fixing UI components, closes #137

app/login/page.tsx
Not the best solution for getting it to the center but I think it's good enough for now. Also deleted "back" button which we're not using.
=> style: align center, change colors, closes #111
